### ISSUE TITLE
Complete eye tracker info table in webapp

### ISSUE THREAD

**Issue by isolver** [isolver/Confero#31]
Some data about the eye tracker is being provided to the web app, but it is not complete. Need to:
- [x] Fix fields that are currently static and not changed to appropriate values. For example tracker model name.
- [x] Gaze information is an average of both eyes when binocular data is available (and valid). Need to add some info about each eye as well:
  - each eye position
  - each eye pupil size  

For both average and individual eye data, add:
- [x] Noise level calculation. (Need to agree on what measure is best for this, stdev, RMS, other??)
- [x]  % of samples collected over the last second that contained missing data. If % of invalid samples goes above a threshold % (settable in config), change the color of the table cell background. Perhaps have 2 thresholds, each using a different color for background.
- [x] % of samples from last second where the gaze position is outside the 'acceptable gaze value range'. This can be defined by a multiplier in the config file. For example setting it to 1.1 would make the valid tracking range be 110% of what the gaze coord range for the screen itself would be. Also, perhaps have 2 thresholds used to control the 'warning' or 'error' color used for the appropriate table cell backgrounds.
