### ISSUE TITLE
Eye Tracker Device Info Issues

### ISSUE THREAD

**Issue by isolver** [isolver/Confero#65]
- [x] as the values change they move the table cell widths. Cells should be fixed width.
- [x] clean up number formats. I think Gary wants ints for any position data.
- [x] looks like RMS calculation may have a bug. Stdev looks OK. 
- [x] Also looks like eye tracker info is being updated event sample and not using the update interval value for the device.
